### ISSUE TITLE
阅读code时候有个疑问

### ISSUE THREAD

**Issue by ddr8848** [isghost/kaixinxiaoxiaole#1]
你好，正在学习研究js,看到三消初始化这里，有处逻辑没有看明白，GameModel.prototype.init方法下面。` for(var i = 1;i<=GRID_WIDTH;i++){
        for(var j = 1;j <= GRID_HEIGHT;j++){
            let flag = true;
            while(flag){
                flag = false;
                this.cells[i][j].init(this.getRandomCellType());
                let result = this.checkPoint(j, i)[0];//???why j, i?
                if(result.length > 2){
                    flag = true;
                }
                this.cells[i][j].setXY(j, i);
                this.cells[i][j].setStartXY(j, i);
            }
        }
    }
`
为何checkPoint 还有setXY, setStartXY 传入的 都是j,i. 我的理解不是应该是i, j？
但是运行结果来看。j, i是对的。请问有空解惑吗？谢谢！

**Comment by isghost** [comment]
![image](https://user-images.githubusercontent.com/6837511/34913012-d0a6f2dc-f92b-11e7-9b7c-865de2dcceab.png)

**Comment by ddr8848** [comment]
你好！谢谢你的回复。
我后来把所有j,i 改成了i,j.
这样理解起来比较方便。
我借用你的code为基础正在做一个自己的小玩意儿。

thanks a lot!

2018-01-14 13:07 GMT+08:00 焱 <notifications@github.com>:

**Comment by isghost** [comment]
[ok]

**Comment by MarsZone** [comment]
+1...我也困惑了好久,还想发邮件问下作者.

**Comment by MarsZone** [comment]
还有我不是很明白
vis[x + y * 9] = true; 这个干嘛用?

**Comment by isghost** [comment]
> 还有我不是很明白
> vis[x + y * 9] = true; 这个干嘛用?


下面有段代码用到，防止重复遍历
if (tmpX < 1 || tmpX > 9
                    || tmpY < 1 || tmpY > 9
                    || vis[tmpX + tmpY * 9]
                    || !this.cells[tmpY][tmpX]) {
                    continue;
                }

你可以学习一下宽度优先搜索算法
