### ISSUE TITLE
关于mask组件 和 CellView 

### ISSUE THREAD

**Issue by liveiu** [isghost/kaixinxiaoxiaole#2]
请教一下 mask组件 和 CellView如何关联，感谢

**Comment by isghost** [comment]
`目前的逻辑没有什么特别关联`
如果你的目标是处理不规则的网格，那么只需要添加额外的IMAGE_STENCIL
感觉我没有get到你的问题要点

**Comment by liveiu** [comment]
是的，就是准备做处理不规则的网格的消除，creator1.8的Mask好实现吗？貌似只能用imageStencil...

**Comment by isghost** [comment]
这个用imageStencil应该还是好实现的，加油
