### ISSUE TITLE
怎么添加分数统计呢

### ISSUE THREAD

**Issue by jihan513** [isghost/kaixinxiaoxiaole#4]
看了代码，感觉有点复杂，不知道在哪下手

**Comment by isghost** [comment]
首先分数计算肯定在Model层
然后分数肯定是根据消除的格子数量的时候计算
格子的消除在processCrush 函数的最下面
或者你直接搜索消除，应该就能找到

**Comment by jihan513** [comment]
消除的格子数量是 cycleCount 吗

**Comment by isghost** [comment]
不是，你打印日志看下吧

**Comment by jihan513** [comment]
我看懂了 谢谢你
