### ISSUE TITLE
bug:如果消除了四个，移动的那个方块没有消除

### ISSUE THREAD

**Issue by huangXin1538** [isghost/kaixinxiaoxiaole#7]

**Comment by isghost** [comment]
那是高级方块♢


 
---原始邮件---
发件人: "huangXin1538"<notifications@github.com>
发送时间: 2019年5月30日(星期四) 晚上6:22
收件人: "isghost/kaixinxiaoxiaole"<kaixinxiaoxiaole@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [isghost/kaixinxiaoxiaole] bug:如果消除了四个，移动的那个方块没有消除 (#7)
